apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: amit-seth   # replace with the name of profile you want, this will be user's namespace name
spec:
  owner:
    kind: User
    name: amit-seth   # replace with the email of the user

  resourceQuotaSpec:    # resource quota can be set optionally
   hard:
     cpu: "8"
     memory: "32Gi"
     requests.nvidia.com/gpu: "2"
     requests.nvidia.com/mig-3g.20gb: "2"
     persistentvolumeclaims: "1"
     requests.storage: "50Gi"
